spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tutorsquare
    username: postgres 
    password: aditya
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: create-drop
    show-sql: true

